name: Reusable Workflow B

on:
    workflow_call:

jobs:
    B:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo "Reusable workflow B was triggered!"

    call-c:
        uses: ./.github/workflows/reusable_c.yml
