name: Reusable Workflow A

on:
    workflow_call:

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Hello
              run: echo "Reusable workflow A was triggered!"
    call-b:
        uses: ./.github/workflows/reusable_b.yml
