name: Reusable Workflow A

on:
    workflow_call:

jobs:
    A:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo "Reusable workflow A was triggered!"

    call-b:
        uses: ./.github/workflows/reusable_b.yml
